services:
  postgres:
    image: postgres:16-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PGADMIN_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "127.0.0.1:5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app_network

  migrations:
    build: .
    restart: "no"

    env_file:
      - .env

    environment:
      POSTGRES_HOSTNAME: postgres

    command: [ "alembic", "upgrade", "head" ]

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - app_network

  bot:
    build: .
    working_dir: /app
    container_name: ${BOT_CONTAINER_NAME}
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - PYTHONUNBUFFERED=1

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - app_network

  db_backup:
    image: prodrigestivill/postgres-backup-local:16
    restart: unless-stopped

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 90

    volumes:
      - ./backups:/backups

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - app_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app_network

volumes:
  postgres_data:
  pgadmin_data:
  portainer_data:

networks:
  app_network:
    driver: bridge