"""remove daily_bonus_at

Revision ID: 9dedc2fd37a9
Revises: ababca25b3a0
Create Date: 2026-09-08 18:03:28.849419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dedc2fd37a9'
down_revision: Union[str, Sequence[str], None] = 'ababca25b3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotteries')
    op.drop_column('users', 'daily_bonus_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_bonus_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_table('lotteries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bet_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chosen_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('winning_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_won', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('earned', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], name=op.f('lotteries_telegram_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lotteries_pkey'))
    )
    # ### end Alembic commands ###
