"""add daily_bonus_at

Revision ID: ababca25b3a0
Revises: 
Create Date: 2026-09-08 14:12:47.868666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ababca25b3a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotteries')
    op.add_column('users', sa.Column('daily_bonus_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_bonus_at')
    op.create_table('lotteries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bet_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chosen_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('winning_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_won', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('earned', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], name=op.f('lotteries_telegram_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lotteries_pkey'))
    )
    # ### end Alembic commands ###
