"""empty message

Revision ID: ea1dec79f33e
Revises: 
Create Date: 2026-09-24 06:35:16.900915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1dec79f33e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_members', 'chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('chat_members_user_id_fkey'), 'chat_members', type_='foreignkey')
    op.drop_constraint(op.f('chat_members_chat_id_fkey'), 'chat_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_members', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.alter_column('moderator_actions', 'chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('moderator_actions', 'moderator_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('moderator_actions', 'target_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderator_actions', 'target_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('moderator_actions', 'moderator_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('moderator_actions', 'chat_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.create_foreign_key(op.f('chat_members_chat_id_fkey'), 'chat_members', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('chat_members_user_id_fkey'), 'chat_members', 'users', ['user_id'], ['id'])
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('chat_members', 'chat_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
