bot_responses:
  - "Ась?"
  - "Да завали ебало уже"
  - "Чего тебе?"
  - "Шо"
  - "Ну говори"
  - "Чего уставился"
  - "Чо те?"
  - "Кого?"
  - "Что?"
  - "не мешай"
  - "да?"
  - "Проблемы ебать?"
  - "Ты проблядонская рогатка, чо ты доебался до меня?"
  - "Да сука сам ты бот, был бы я твоим отцом я бы тебя пиздил каждый день"
  - "Я"
  - "Чо такое?"
  - "Слушаю"
  - "ау?"
  - "чо бля?"
  - "Тут я"
  - "Шо ты хочешь?"
  - "Чо вы доебались?"
  - "Ну и чё?"
  - "Серьёзно?"
  - "Блять, реально?"
  - "Ну и хуй с ним"
  - "Руки не из жопы?"
  - "Ага, конечно"
  - "С тобой всё норм?"
  - "Ты кто вообще?"
  - "Всё, хватит"
  - "Завязывай"
  - "Сам бот"
  - "Шо"
  - "Чо я?"
  - "Нахуя припёрся?"
  - "Хули?"
  - "Шо ты маленький?"
  - "Давай без истерик"
  - "Бездарям не положено отвечать"
  - "Хули ты хочешь?"
  - "Ого"
  - "Занят, иди нахуй"
  - "Ну и ладно"
  - "Ну я и чо"
  - "Что хотел-то?"
  - "Что опять надо"
  - "типо я"
  - "Да иди нахуй"
  - "Эмм чел"
  - "Да отстань уже"
  - "Отвали короче"
  - "Говори быстрее"
  - "Ну?"
  - "Не позорься"
  - "Делом займись уже"
  - "Хуеглот"
  - "всё динаху"
  - "Да ну что опять"
  - "А?"
  - "Что такое?"
  - "тупо я"
  - "Ты мне в иерархии не нужен"
  - "Я думал, у тебя есть вопросы"
  - "Я не прислуга"
  - "Мне лень даже отвечать"
  - "Пиши быстрее"
  - "Ну и всё?"
  - "Чо молчишь?"
  - "Иди делом займись"
  - "Всё, я ушёл"
  - "и чо опять хочешь ты от меня?"
  - "Чо вы доебались?"
  - "Чо ебать?"
  - "Шо там?"
  - "Я в работе"
  - "К вашему слугу"
  - "Чо надо нищета?"
  - "Да не ори бездарь"
  - "Я не одобряю твоё поведение"
  - "Хули надо?"
  - "Чо такое эу?"
  - "Да стяни ебальник"
  - "Шо там?"
  - "Давай, удиви меня"
  - "Тебе скучно?"
  - "И?"
  - "Сдурел совсем?"
  - "Слабоумный что-ли?"


assets:
  kagune:
    obtained_gif:
      CgACAgIAAxkBAAIlNmqATGAcOxl8rN9FBU9SeYDAiMbhAAKLogACRhYJSBylRFc7drcqPQQ
    gifs:
      1: "CgACAgIAAxkBAAIXOWogEZbP4gjJYXrxbv5Zb1wfZcrYAAIwmAACPWIAAUmKhp_uXnxO9DsE"
      20: "CgACAgIAAxkBAAIXOGogEYmMfnOPAAG4yRWcM_j5xgLFbAACLpgAAj1iAAFJt8uluSrQSf47BA"
      35: "CgACAgIAAxkBAAIXOmogEZl8oiBB92h-dfPmk8BDfhcaAAIxmAACPWIAAUml5ZPClu291jsE"
      50: "CgACAgIAAxkBAAIWxmoeux7nTQJHjvcynZLGXtVidh39AAL8mQACA1v5SLz78CubtPsrOwQ"
      60: "CgACAgIAAxkBAAIWzWoeux6SMbqwn-25VF8ltkS_HhIiAAIPmgACA1v5SDr97giYqlHFOwQ"
      75: "CgACAgIAAxkBAAIWy2oeux6oNmXur6Cwl8i7KCfViAvtAAICmgACA1v5SLSR9Xtk_OHJOwQ"
      90: "CgACAgIAAxkBAAIWyWoeux7Af4ahvgkO1f4PZLrZXGf4AAL_mQACA1v5SIm4GHzJrBjOOwQ"
      110: "CgACAgIAAxkBAAIWzGoeux4mc3_QqX5ob8ZQXRfKoUwKAAIDmgACA1v5SAvcSNEVXbr6OwQ"
      130: "CgACAgIAAxkBAAIWymoeux71REmEZdMOj9TZdsxX2Z5DAAOaAAIDW_lIM_ziCIMggg47BA"
      150: "CgACAgIAAxkBAAIWyGoeux6E0NMMhR7HEIVcAZ5pdhApAAL-mQACA1v5SKaP0XCdvZuGOwQ"
      175: "CgACAgIAAxkBAAIWxGoeux6SDoASRlEktXpmVdwXLBPqAAL4mQACA1v5SASBlMs5Fj9mOwQ"
      185: "CgACAgIAAxkBAAIWxWoeux6kvjTRf-AiDI2QZMLzd4JBAAL5mQACA1v5SNZJC66sSChFOwQ"
      200: "CgACAgIAAxkBAAIXN2ogEX3JuZqPlmUg-GbH2Gte9igFAAIsmAACPWIAAUm48SYAAeAobwc7BA"

  snap:
    gifs:
      - "CgACAgIAAxkBAAIJE2nvcQg6K6XV4oUM6OFbMs0XgQABcgACX6EAArt4gUsiHJ440A5yNTsE"
      - "CgACAgIAAxkBAAIJFGnvcQjFCaBiAjyab7E7OzzBylKSAAJhoQACu3iBS7AILJY3gOgwOwQ"
      - "CgACAgIAAxkBAAIJFWnvcQha1L6ZypBvWUrz8K_wufTfAAJxoQACu3iBS00frqtC-5qrOwQ"
      - "CgACAgIAAxkBAAIlPWqAZfEoaYvkN521OO6SdrX5RAV-AAJKowACRhYJSFzjKp-SmZoIPQQ"
      - "CgACAgIAAxkBAAIlP2qAZiWYdmmTlFPhM-mMZcBLId_CAAJMowACRhYJSOdfc5WpbkixPQQ"
      - "CgACAgIAAxkBAAIJEGnvcQhb9fVFUFRubGqggQLr24HWAAJZoQACu3iBS6Oa9K34CAZkOwQ"
      - "CgACAgIAAxkBAAIJEWnvcQi3W98ohO4gulB6E3Z4iu-sAAJboQACu3iBSz5iv0olthBUOwQ"
      - "CgACAgIAAxkBAAIJEmnvcQjSMjxnirXMAWUpYml6xPhvAAJeoQACu3iBSxV6nZG3-lRFOwQ"
     
  coffee:
    gifs:
      - "CgACAgIAAxkBAAIPXmoDLlhCMmzTEyUh_1xFXaNv54UoAAIQnwACmYgYSMJDIot88JyVOwQ"
      - "CgACAgIAAxkBAAIPX2oDLl7EXRI1mbQ9qmklzcF87-ynAAIRnwACmYgYSJymgC1th9y2OwQ"
      - "CgACAgIAAxkBAAIPYGoDLmAmA4nC9QNR_TRkr0CNZHagAAISnwACmYgYSIanErEfpdDaOwQ"
      - "CgACAgIAAxkBAAIlVmqAb9mnim8XqGYpbGgvruRiHnX-AALhowACRhYJSJDsWwnCu-khPQQ"
      - "CgACAgIAAxkBAAIlWGqAb-Z1J4mUNoeUUZ8WTrs8gpuZAALiowACRhYJSLbzChi4ZP00PQQ"
      - "CgACAgIAAxkBAAIPYWoDLmerwyUhnpfJsYwxS2F64NXzAAIVnwACmYgYSGSY4JAYkWKKOwQ"
      - "CgACAgIAAxkBAAIPYmoDLmy0TwVbVZtfwzuGNIuUBFNrAAIWnwACmYgYSHLeqLVu09u7OwQ"


message:
  start: |
      <b>Добро пожаловать в BlaZe | Bot</b>
      
      <i>Ты оказался в месте, где не всё так просто, как кажется. Здесь каждый скрывает свою истинную сущность.</i>
      
      <tg-emoji emoji-id="5258461531464539536">📌</tg-emoji> Ознакомься с командами.
  text_is_subscription: |
    <b><tg-emoji emoji-id="5290027337771919383">😒</tg-emoji> Добро пожаловать в BlaZe | Bot</b>
      
    <i>Ты оказался в месте, где не всё так просто, как кажется. Здесь каждый скрывает свою истинную сущность.</i>
    
    <tg-emoji emoji-id="6037175527846975726">🎁</tg-emoji> Подписан на канал, держи бонус от — <b>Blaze</b> в размере <b>{bonus_money}</b> BlazeCoin
      
    <tg-emoji emoji-id="5258461531464539536">📌</tg-emoji> Ознакомься с командами.

  help:
    help_text: |
     <b>BlaZe | Bot — Навигация </b>
    
     <i>В этом городе нет простых путей. Выживают только те, кто понимает правила. Ознокомься со всем ниже.</i>
    
     <b>Ссылка на канал с лором:</b>
    back_help: |
      <b>Добро пожаловать в BlaZe | Bot</b>
      
      <i>Ты оказался в месте, где не всё так просто, как кажется. Здесь каждый скрывает свою истинную сущность.</i>
      
      <tg-emoji emoji-id="5258461531464539536">📌</tg-emoji> Ознакомься с командами.

  balance:
    balance_text: |
      <tg-emoji emoji-id="5258204546391351475">💵</tg-emoji> <b>Баланс - <code>{name}</code></b>
        
      <tg-emoji emoji-id="5864068125112144897">💸</tg-emoji> <b>Текущий балик:</b> {money} BlazeCoin
        
      <tg-emoji emoji-id="5258336354642697821">⬇️</tg-emoji> Посмотри на настоящих богачей в топе
    top_balance_text: |
      <tg-emoji emoji-id="5258204546391351475">💵</tg-emoji> <b>Баланс — <code>{name}</code></b>
        
      <tg-emoji emoji-id="5864068125112144897">💸</tg-emoji> <b>Текущий балик:</b> {money} BlazeCoin

  transfer:
    translation: | 
      <tg-emoji emoji-id="5260416304224936047">✅</tg-emoji> Переведено <b>{amount}</b> BlaZeCoin пользователю <code>{receiver_id}</code>.
      
      <tg-emoji emoji-id="5258204546391351475">💵</tg-emoji> Твой баланс: <b>{new_sender_balance}</b>

  coffee:
    coffee_snap_limit: |
      <tg-emoji emoji-id="5386470514871003633">☕️</tg-emoji> <b>Кафе «Антейку»</b>
    
      <i>Бесплатный кофе не дают просто так бездарям вроде тебя.</i>
    
      <tg-emoji emoji-id="5258503720928288433">ℹ️</tg-emoji> Сломай ещё — <b>{needed} пальцев</b>, чтобы насладиться чашечкой ароматного кофе в <b>«Антейку».</b>

    overdose_1: |
      <tg-emoji emoji-id="5386313314773002654">⚠️</tg-emoji> <b>Ты словил передоз</b>
    
      <i>Тебе же сказали ждать 30 минут.</i> <i>Но нет, тебе обязательно понадобилось выпить кофе еще раз.</i>
    
      <tg-emoji emoji-id="5258258882022612173">⏲️</tg-emoji> Отдыхай теперь <b>5 часов</b> и приходи в себя.
    overdose_2: |
      <tg-emoji emoji-id="5386313314773002654">⚠️</tg-emoji> <b>Состояние: передоз</b>
    
      <i>Ты выпил слишком много кофе и валяешься на полу кафе.</i>
    
      <tg-emoji emoji-id="5258258882022612173">⏲️</tg-emoji> Очнёшься через: <b>{time}</b>

    coffee_up: |
      <tg-emoji emoji-id="5386470514871003633">☕️</tg-emoji> <b>Ты выпил чашечку кофе</b>
    
      <tg-emoji emoji-id="5936143551854285132">📊</tg-emoji> Выпито кофе: <code>{coffee_total}</code>
      <tg-emoji emoji-id="5864068125112144897">💸</tg-emoji> Поднял бабла: <code>+{money}</code>
    
      <tg-emoji emoji-id="5258258882022612173">⏲️</tg-emoji> Следующую чашечку советуем пить через 30 минут.

  kagune:
    cooldown:
      message: |
        <tg-emoji emoji-id="5442804822048780010">😫</tg-emoji> <b>Да успокойся ты нахуй.</b> 
        
        <i>Куда ты торопишься? Кагуне тебе что, за секунду прокачиваться должно?</i>
        
        <tg-emoji emoji-id="5258258882022612173">⏲️</tg-emoji> Следующая прокачка будет доступна через — <b>{time}</b>
      callback: |
        🧬 Да успокойся ты нахуй.
        
        Куда ты торопишься? Кагуне тебе что, за секунду прокачиваться должно?
        
        ⏲️ Следующая прокачка будет доступна через — {time}

    not_enough_money:
      message: | 
        <tg-emoji emoji-id="5258204546391351475">💵</tg-emoji> <b>Капец ты нищий.</b> 
        
        <i>Денег иди сначала заработай, а потом кагуне качай.</i>
        
        <tg-emoji emoji-id="5864068125112144897">💸</tg-emoji> Для прокачки твоего кагуне тебе не хватает: <b>{missing} BlazeCoin</b> 
      callback: |
        💵 Капец ты нищий.
        
        Денег иди сначала заработай, а потом кагуне качай.
        
        💸 Для прокачки твоего кагуне тебе не хватает: {missing} BlazeCoin 

    kagune_1: |
      <tg-emoji emoji-id="5346175694340634914">🌺</tg-emoji> <i>Готов ли ты стать гулем и принять свою истинную силу? Готов ли ты справиться со своим кагуне?</i>
    
      <b>Прими же себя, {name}</b>
    kagune_2: |
      <tg-emoji emoji-id="5406716483898201012">🌺</tg-emoji> Что ж, <b>{name}</b>, ты пробудил своё кагуне и отныне...Ты гуль.
    
      <i>Пути назад больше нет...С этого дня тебе предстоит жить между двумя мирами, не принадлежа ни одному из них.</i>
    
      <tg-emoji emoji-id="5442804822048780010">😫</tg-emoji> Твой тип кагуне — <b>{chosen_type}</b>
    kagune_up: |               
      <tg-emoji emoji-id="5442804822048780010">😫</tg-emoji> <b>Ты усилил своё кагуне</b>
    
      <tg-emoji emoji-id="5936143551854285132">📊</tg-emoji> Его текущий уровень: <code>{new_lvl}</code>
      <tg-emoji emoji-id="5864068125112144897">💸</tg-emoji> Потрачено денег: <code>-{price}</code>
    
      <tg-emoji emoji-id="5258258882022612173">⏲️</tg-emoji> Следующая прокачка доступна через 15 минут.

  snap:
    snap_cooldown: |
      <tg-emoji emoji-id="5834596128246469018">🫰</tg-emoji> <b>А вот нихуя не щелк!</b>
    
      <i>Куда ты щелкаешь, ещё 10 минут не прошло.</i>
    
      <tg-emoji emoji-id="5258258882022612173">⏲️</tg-emoji> Остаётся ждать: <b>{time}</b>
      <tg-emoji emoji-id="5294080678797800392">🩹</tg-emoji> Пальчик восстанавливается
    snap_up: |
      <tg-emoji emoji-id="5834596128246469018">🫰</tg-emoji> <b>Пальчик сломан</b>
    
      <tg-emoji emoji-id="5936143551854285132">📊</tg-emoji> Сломано пальцев: <code>{total_snap}</code>
      <tg-emoji emoji-id="5864068125112144897">💸</tg-emoji> Поднял деняк кеш: <code>+{money_won}</code>

      <tg-emoji emoji-id="5258258882022612173">⏲️</tg-emoji> Cледующая попытка через 10 минут.

  quiz:
    quiz_limit:
      callback: |
        💬 Лимит вопросов исчерпан на сегодня, дегенерат.

        Ты ответил на все доступные вопросы.

        ⏲️ Жди до следующего дня.
      message: |
        <tg-emoji emoji-id="5936035091045159318">💬</tg-emoji> <b>Лимит вопросов исчерпан на сегодня, дегенерат.</b>
        
        <i>Ты ответил на все доступные вопросы.</i>
        
        <tg-emoji emoji-id="5258258882022612173">⏲️</tg-emoji> Жди до следующего дня.
    right:
      верно
    incorrect:
      неверно
    no_questions: |
      <tg-emoji emoji-id="6043960760130868895">🤔</tg-emoji> <b>А вопросов-то и нет.</b>
      
      <i>Викторина пуста — либо ты уже всё ответил, либо новых вопросов пока не завезли.</i>
      
      <tg-emoji emoji-id="5258258882022612173">⏲️</tg-emoji> Загляни немого позже.
    no_questions_callback: |
     🕳 Пусто. Вопросы закончились или отсутствуют.

  lottery:
    win: |
      <tg-emoji emoji-id="5915833712368424979">🎰</tg-emoji> Депнул на <b>{chosen_color}</b>
      
      <tg-emoji emoji-id="6041731551845159060">🎉</tg-emoji> <b>Выиграл!</b>
      Победный цвет был <b>{winning_color}</b>
      
      <tg-emoji emoji-id="5890848474563352982">💰</tg-emoji> Твой выигрыш: <b>+{earned}</b> BlaZeCoin
      <tg-emoji emoji-id="5938539885907415367">📈</tg-emoji> Множитель: <b>×{multiplier}</b>

      <tg-emoji emoji-id="5258204546391351475">💵</tg-emoji> Баланс: <b>{money}</b> BlaZeCoin

    lose: |
      <tg-emoji emoji-id="5915833712368424979">🎰</tg-emoji> Депнул на <b>{chosen_color}!</b>
      
      <tg-emoji emoji-id="5260342697075416641">❌</tg-emoji> <b>Проиграл!</b>
      Победный цвет был <b>{winning_color}</b>
      
      <tg-emoji emoji-id="5864068125112144897">💸</tg-emoji> Ты потерял: <b>{bet}</b> BlaZeCoin
      
      <tg-emoji emoji-id="5258204546391351475">💵</tg-emoji> Баланс: <b>{money}</b> BlaZeCoin

  stats:
    stats_text: |
      <tg-emoji emoji-id="5258204546391351475">💵</tg-emoji> <b>Балик:</b> <code>{money} BlazeCoin</code>
    
      <tg-emoji emoji-id="5834929920219812289">💪</tg-emoji> <b>Сила:</b> <code>{strength}/100 {p_strength}</code>
      <tg-emoji emoji-id="5834678930920969133">🦶</tg-emoji> <b>Ловкость:</b> <code>{dexterity}/100 {p_dexterity}</code>
      <tg-emoji emoji-id="5276139556725350230">🏃‍♀️</tg-emoji> <b>Скорость:</b> <code>{speed}/100 {p_speed}</code>
      <tg-emoji emoji-id="5938368005611195877">❤️</tg-emoji> <b>Макс. здоровье</b>: <code>{hp}/100 {p_hp}</code>
      <tg-emoji emoji-id="5834967608557835277">❣️</tg-emoji> <b>Регенерация:</b> <code>{regen}/100 {p_regen}</code>
    notifications:
      invalid_stat: "⚠️ Неизвестный стат"
      invalid_amount: "⚠️ Ошибка прокачки"
      maxed: "🔝 Стат прокачан до максимума"
      not_enough_money: "💲 Недостаточно BC на балике"
      db_error: "⚠️ Ошибка транзакции балика"

  not_ghoul:
    not_ghoul_message: |
      <tg-emoji emoji-id="5264782039697080626">😒</tg-emoji> <b>Ты не гуль.</b> 
      
      <tg-emoji emoji-id="5258503720928288433">ℹ️</tg-emoji> <i>Пробуди своё кагуне и прими свою сущность через команду</i> — <b>«растить кагуне»</b>
    not_ghoul_callback:
      👁‍🗨 Ты не гуль. Получи кагуне и стань гулем.

  middleware_text_antispam:
    ⏳ Воооу, стопэ. Одно нажатие — достаточно

  tops:
    prefixes:
        "1": "<tg-emoji emoji-id='5834643712189141114'>👑</tg-emoji> "
        "2": "<tg-emoji emoji-id='5447203607294265305'>🥈</tg-emoji> "
        "3": "<tg-emoji emoji-id='5453902265922376865'>🥉</tg-emoji> "
    top_money:
      not_money:
        "\n<tg-emoji emoji-id='5299024976429466492'>🤡</tg-emoji> Боже, в общий топ хотяб войди, не позорься"
      rank_messages:
        "1": "\n<tg-emoji emoji-id='5289722755871162900'>👑</tg-emoji> Отныне, ты самый богатый гуль в истории."
        "2": "\n<b>Ты на 2-ом месте</b> и теперь не являешься бездарем."
        "3": "\n<b>Ты вошёл в тройку миллионеров по BlazeCoin!</b>"
        "4": "\n<tg-emoji emoji-id='5258084656674250503'>🚪</tg-emoji> <i>Ты на <b>{rank}—м</b> месте, бездарь</i>"
    top_kagune:
      top_1_status:
        "\n<tg-emoji emoji-id='5442804822048780010'>😫</tg-emoji> <i>Гуль по имени {name} является самым сильным среди всех.</i>"
